name: Soroban
options:
  bundleIdPrefix: com.japanesesoroban
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.3.2"
    CURRENT_PROJECT_VERSION: "2"
    DEVELOPMENT_TEAM: 83VGKGSQUH
    CODE_SIGN_STYLE: Automatic
targets:
  Soroban:
    type: application
    platform: iOS
    sources:
      - path: Soroban
    info:
      path: Soroban/Info.plist
      properties:
        CFBundleDisplayName: Japanese Soroban
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: "1.3.2"
        CFBundleVersion: "2"
        LSRequiresIPhoneOS: true
        UIRequiresFullScreen: true
        ITSAppUsesNonExemptEncryption: false
        UIDeviceFamily:
          - 1
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        LSApplicationCategoryType: public.app-category.education
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1"
        PRODUCT_BUNDLE_IDENTIFIER: com.japanesesoroban.app
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
